# Generated by Django 4.2.7 on 2023-12-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.RemoveField(
            model_name='record',
            name='creation_date',
        ),
    ]
